---
- name: Provisionning anthony's debian based environment
  hosts: all
  become: true
  tasks:
    # register content of /usr/bin/env in an ansible variable
    - name: load content of /usr/bin/env
      ansible.builtin.shell: env
      register: env_content

    # update package list
    - name: update package list
      ansible.builtin.apt:
        update_cache: yes

    # upgrade packages
    - name: upgrade package list
      ansible.builtin.apt:
        upgrade: "yes"

    # utils
    - name: install utils
      ansible.builtin.apt:
        name: "{{ utils_packages }}"
        state: latest
      vars:
        utils_packages:
          - coreutils
          - desktop-file-utils
          - apt-utils
          - xz-utils
          - gnupg
          - vim
          - curl
          - wget
          - xdg-utils
          - gzip
          - zip
          - man-db
          - tree
          - ssh

    # wslu (utils for WSL)
    # - name: install wslu (1/5) | install required packages
    #   ansible.builtin.apt:
    #     name: "{{ wsl_utils_packages }}"
    #     state: present
    #   vars:
    #     wsl_utils_packages:
    #       - gnupg2
    #       - apt-transport-https
    # - name: install wslu (2/5) | create keyring file to host the public key
    #   ansible.builtin.file:
    #     path: /etc/apt/trusted.gpg.d/wslu.asc
    #     state: touch
    #     mode: u=rw,g=r,o=r
    # - name: install wslu (3/5) | download package repository's public key
    #   ansible.builtin.apt_key:
    #     url: https://pkg.wslutiliti.es/public.key
    #     state: present
    #     keyring: /etc/apt/trusted.gpg.d/wslu.asc
    # - name: install wslu (4/5) | add package repository to the sources list
    #   ansible.builtin.apt_repository:
    #     repo: deb https://pkg.wslutiliti.es/debian bullseye main
    #     state: present
    # - name: install wslu (5/5) | install wslu package
    #   ansible.builtin.apt:
    #     name: wslu
    #     state: present
    #     update_cache: yes

    # git
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest

    # gh
    - name: install gh
      ansible.builtin.apt:
        name: gh
        state: latest

    # vscode
    - name: install vscode
      ansible.builtin.apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

    # nodejs
    - name: install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: latest

    # npm
    - name: install npm
      ansible.builtin.apt:
        name: npm
        state: latest

    # okular
    # - name: install okular
    #   ansible.builtin.apt:
    #     name: okular
    #     state: latest

    # #firefox
    # - name: uninstall firefox
    #   ansible.builtin.apt:
    #     name: firefox-esr
    #     state: absent

    # set alias expansion
    - name: set alias expansion in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertbefore: "EOF"
        line: "\nshopt -s expand_aliases"
        state: present

    - name: set custom alias 'll' in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertafter: "EOF"
        line: 'alias ll="ls -lh"'
        state: present

    - name: set custom alias 'la' in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertafter: "EOF"
        line: 'alias la="ls -lha"'
        state: present

    - name: set custom alias 'lt' in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertafter: "EOF"
        line: 'alias lt="tree"'
        state: present

    - name: set custom alias 'drive' in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertafter: "EOF"
        line: 'alias drive="cd /mnt/g/"'
        state: present

    - name: set custom alias 'windows' in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertafter: "EOF"
        line: 'alias windows="cd /mnt/c/"'
        state: present

    - name: set custom alias 'open' for 'xdg-open' in /etc/bash.bashrc
      ansible.builtin.lineinfile:
        path: /etc/bash.bashrc
        insertafter: "EOF"
        line: 'alias open="xdg-open"'
        state: present
      when: env_content.stdout.find('WSL') != -1

    # - name: set custom alias 'open' for 'wsl-open' in /etc/bash.bashrc
    #   ansible.builtin.lineinfile:
    #     path: /etc/bash.bashrc
    #     insertafter: "EOF"
    #     line: 'alias open="wsl-open"'
    #     state: present
    #   when: env_content.stdout.find('WSL') == -1
