---
- name: Provisionning anthony's debian based environment
  hosts: all
  become: true
  tasks:
    # update package list
    - name: update package list
      ansible.builtin.apt:
        update_cache: yes

    # upgrade packages
    - name: upgrade package list
      ansible.builtin.apt:
        upgrade: "yes"

    # utils
    - name: install utils
      ansible.builtin.apt:
        name: "{{ utils_packages }}"
        state: latest
      vars:
        utils_packages:
          - coreutils
          - desktop-file-utils
          - apt-utils
          - xz-utils
          - gnupg
          - vim
          - curl
          - wget
          - xdg-utils
          - gzip
          - zip
          - man-db
          - tree
          - ssh

    # wslu (utils for WSL)
    - name: install wslu (1/5) | install required packages
      ansible.builtin.apt:
        name: "{{ wsl_utils_packages }}"
        state: latest
      vars:
        wsl_utils_packages:
          - gnupg2
          - apt-transport-https
    - name: install wslu (2/5) | create keyring file to host the public key
      ansible.builtin.file:
        path: /etc/apt/trusted.gpg.d/wslu.asc
        state: touch
        mode: u=rw,g=r,o=r
    - name: install wslu (3/5) | download package repository's public key
      ansible.builtin.apt_key:
        url: https://pkg.wslutiliti.es/public.key
        state: present
        keyring: /etc/apt/trusted.gpg.d/wslu.asc
    - name: install wslu (4/5) | add package repository to the sources list
      ansible.builtin.apt_repository:
        repo: deb https://pkg.wslutiliti.es/debian bullseye main
        state: present
    - name: install wslu (5/5) | install wslu package
      ansible.builtin.apt:
        name: wslu
        state: latest
        update_cache: yes

    # git
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest

    # gh
    - name: install gh
      ansible.builtin.apt:
        name: gh
        state: latest

    # # vscode
    # - name: install vscode
    #   ansible.builtin.apt:
    #     deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

    # nodejs
    - name: install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: latest

    # npm
    - name: install npm
      ansible.builtin.apt:
        name: npm
        state: latest

    # okular
    # - name: install okular
    #   ansible.builtin.apt:
    #     name: okular
    #     state: latest

    # set custom aliases
    - name: set custom alias 'll' in /home/anthony/.bashrc
      ansible.builtin.lineinfile:
        path: /home/anthony/.bashrc
        insertafter: "^# some more ls aliases"
        line: 'alias ll="ls -lh"'
        state: present

    - name: set custom alias 'la' in /home/anthony/.bashrc
      ansible.builtin.lineinfile:
        path: /home/anthony/.bashrc
        insertafter: "^# some more ls aliases"
        line: 'alias la="ls -lha"'
        state: present

    - name: set custom alias 'lt' in /home/anthony/.bashrc
      ansible.builtin.lineinfile:
        path: /home/anthony/.bashrc
        insertafter: "^# some more ls aliases"
        line: 'alias lt="tree"'
        state: present

    - name: set custom alias 'drive' in /home/anthony/.bashrc
      ansible.builtin.lineinfile:
        path: /home/anthony/.bashrc
        insertafter: "^# some more ls aliases"
        line: 'alias drive="cd /mnt/g/"'
        state: present

    - name: set custom alias 'windows' in /home/anthony/.bashrc
      ansible.builtin.lineinfile:
        path: /home/anthony/.bashrc
        insertafter: "^# some more ls aliases"
        line: 'alias windows="cd /mnt/c/"'
        state: present

    - name: set custom alias 'open' in /home/anthony/.bashrc
      ansible.builtin.lineinfile:
        path: /home/anthony/.bashrc
        insertafter: "^# some more ls aliases"
        line: 'alias open="xdg-open"'
        state: present
